upload service working
grishick/heo-web pull request #9
Opened 2021-03-17 04:12 UTC by dpolozov

run node awsUpload.js in the services folder

2021-03-17 19:19 UTC, grishick requested changes

2021-03-17 19:19 UTC, grishick commented on src/components/CreateCampaign.js
> +        .then(res => {
I think this needs exception handling in addition to handling response status codes. E.g., what happens if you pull the plug on the internet when this runs?

2021-03-17 19:19 UTC, grishick commented on tsconfig.json
> +, "services/awsUpload.js"  ]
why do we need to include services/awsUpload.js in TSConfig?

2021-03-17 19:49 UTC, dpolozov commented on tsconfig.json
> +, "services/awsUpload.js"  ]
the system added it on it's own when i was trying to see the .env files. I think that's when it happened. I didn't actually put than in there myself

2021-03-17 21:05 UTC, grishick commented on tsconfig.json
> +, "services/awsUpload.js"  ]
Can you try manually removing it and see if everything still works?

2021-03-17 22:03 UTC, dpolozov commented on tsconfig.json
> +, "services/awsUpload.js"  ]
works without it. removed

2021-03-18 00:26 UTC, grishick approved these changes

2021-03-18 00:26 UTC, merged